---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-jobs
  labels:
    app: jjb
data:
  jenkins_jobs.ini: |-
    [jenkins]
    user=<CENTOS-CI-JENKINS-USERNAME>
    password=<JENKINS-USER-API-TOKEN>
    url=https://jenkins-noobaa.apps.ocp.ci.centos.org
