name: check-number-of-commits2
on: pull_request

jobs:
  check-number-of-commits2:
    runs-on: ubuntu-latest
    steps:
      - uses: nikwotton/Max-Commit-Count@v1.0.0
        with:
          maxCommits: 1
          token: ${{ secrets.GITHUB_TOKEN }}
