name: Nightly Tests

on: workflow_dispatch

jobs:
  nightly-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Run Nightly Tests
        id: run-nightly-tests
        run: |
          make test || exit 1
          docker run --rm -e NEWAWSPROJKEY=${{ secrets.NEWAWSPROJKEY }} \
          -e NEWAWSPROJSECRET=${{ secrets.NEWAWSPROJSECRET }} \
          -e NEWAZUREPROJKEY=${{ secrets.NEWAZUREPROJKEY }} \
          -e NEWAZUREPROJSECRET=${{ secrets.NEWAZUREPROJSECRET }} \
          --name test1 noobaa-tester ./src/test/unit_tests/run_npm_test_on_test_container.sh -s test_s3_ops.js || exit 1
