name: S3 Tests
run-name: ${{ github.actor }} is testing S3 Tests 🚀
# Run on each new PR and each new push to existing PR
on:
  [push, pull_request]

jobs:
  run-s3-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: start minikube
        uses: medyagh/setup-minikube@latest

      - name: run make noobaa
        run: make noobaa NOOBAA_TAG=noobaa-core:s3-tests

      - name: run make tester
        run: make tester TESTER_TAG=noobaa-tester:s3-tests

      - name: run all tests
        run: |
         cd ./src/test/framework/
         sudo ./run_test_job.sh --name ${{ github.actor }} --image noobaa-core:s3-tests --tester_image noobaa-tester:s3-tests --tests_list ./system_tests_list.js --job_yaml ../../../.travis/travis_test_job.yaml --wait
