name: Unit Tests

# Run on each new PR and each new push to existing PR
# on: [push, pull_request]
on: 
  schedule:
    - cron: "0 23 * * *"

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Run Test
        id: run-test
        run: |
          make test || exit 1
          docker run --privileged --rm --name test1 noobaa-tester ./src/test/unit_tests/run_npm_test_on_test_container.sh -s sudo_index.js || exit 1
