name: Weekly Build

# Run every day at 23:00 UTC
on: 
  schedule:
    - cron: "0 23 * * *"

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Build on Operator Repo
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Manual Build Dispatch
          repo: noobaa/noobaa-core
          token: ${{ secrets.GHACCESSTOKEN }}
          inputs: '{ "branch": "master", "tag": "" }' 
